<?= $this->extend('layouts/main') ?><?= $this->section('content') ?>
<div class="d-flex flex-wrap justify-content-between align-items-end page-heading"><div><div class="eyebrow">EXECUTIVE OVERVIEW</div><h1>Attendance Intelligence</h1><p>Ringkasan operasional <?= esc($date) ?> · diperbarui otomatis tiap 30 detik.</p></div><form class="d-flex gap-2 mt-3 mt-lg-0"><input class="form-control" type="date" name="date" value="<?= esc($date) ?>"><select class="form-select" name="department_id"><option value="">Semua divisi</option><?php foreach($departments as $d): ?><option value="<?= $d['id'] ?>" <?= request()->getGet('department_id')==$d['id']?'selected':'' ?>><?= esc($d['name']) ?></option><?php endforeach ?></select><button class="btn btn-primary">Filter</button></form></div>
<?php $cards=['present'=>['Hadir','bi-person-check'],'late'=>['Terlambat','bi-alarm'],'absent'=>['Belum Hadir','bi-person-x'],'working'=>['Sedang Bekerja','bi-briefcase'],'finished'=>['Sudah Pulang','bi-check2-circle'],'overtime'=>['Lembur','bi-moon-stars']]; ?>
<div class="row g-3 mb-4"><?php foreach($cards as $key=>$c): ?><div class="col-6 col-xl-2"><div class="card stat-card dash-card-interactive h-100"><div class="card-body"><div class="d-flex justify-content-between align-items-center"><div class="text-secondary small"><?= $c[0] ?></div><i class="bi <?= $c[1] ?> text-secondary"></i></div><div id="stat-<?= $key ?>" class="display-6 fw-bold mt-2"><?= $stats[$key] ?></div></div></div></div><?php endforeach ?></div>
<div class="row g-4"><div class="col-xl-6"><div class="card dash-card-interactive h-100"><div class="card-header fw-semibold d-flex justify-content-between"><span>Kehadiran 7 Hari</span><span class="text-secondary">LIVE TREND</span></div><div class="card-body"><canvas id="chart"></canvas></div></div></div><div class="col-xl-6"><div class="card dash-card-interactive h-100"><div class="card-header fw-semibold d-flex justify-content-between"><span>Peta Absensi Hari Ini</span><span class="system-status"><span class="live-dot"></span>LIVE</span></div><div id="map"></div></div></div></div>
<?= $this->endSection() ?><?= $this->section('scripts') ?><link href="https://unpkg.com/maplibre-gl@5/dist/maplibre-gl.css" rel="stylesheet"><script src="https://cdn.jsdelivr.net/npm/chart.js"></script><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script src="https://unpkg.com/maplibre-gl@5/dist/maplibre-gl.js"></script><script src="https://unpkg.com/@maplibre/maplibre-gl-leaflet/leaflet-maplibre-gl.js"></script><script>
let initialChart=<?= json_encode($chart,JSON_HEX_TAG) ?>;const attendanceChart=new Chart(document.getElementById('chart'),{type:'bar',data:{labels:initialChart.map(x=>x.date),datasets:[{label:'Hadir',data:initialChart.map(x=>x.total),backgroundColor:'#33e818',borderRadius:6,barThickness:22}]},options:{responsive:true,plugins:{legend:{labels:{color:'#9aa09a',font:{family:'Montserrat',size:10}}}},scales:{x:{ticks:{color:'#727872',font:{family:'Montserrat',size:9}},grid:{display:false}},y:{beginAtZero:true,ticks:{color:'#727872',precision:0,font:{family:'Montserrat',size:9}},grid:{color:'rgba(255,255,255,.05)'}}}}});
const initialPoints=<?= json_encode($locations,JSON_HEX_TAG) ?>,map=L.map('map').setView(initialPoints.length?[initialPoints[0].latitude,initialPoints[0].longitude]:[-8.663626,115.2303082],15),markers=L.layerGroup().addTo(map);L.maplibreGL({style:'https://tiles.openfreemap.org/styles/liberty'}).addTo(map);
function safe(v){return String(v??'').replace(/[&<>"']/g,'')} function draw(points){markers.clearLayers();points.forEach(p=>L.marker([p.latitude,p.longitude]).addTo(markers).bindPopup(`<b>${safe(p.name)}</b><br>${safe(p.check_in_status)}`))} draw(initialPoints);
async function refreshDashboard(){try{const response=await fetch('/api/dashboard/stats'+location.search),json=await response.json();if(!response.ok)return;Object.entries(json.data.stats).forEach(([key,value])=>{const el=document.getElementById('stat-'+key);if(el)el.textContent=value});attendanceChart.data.labels=json.data.chart.map(x=>x.date);attendanceChart.data.datasets[0].data=json.data.chart.map(x=>x.total);attendanceChart.update();draw(json.data.locations)}catch(e){console.warn('Pembaruan dashboard gagal',e)}} setInterval(refreshDashboard,30000);
</script><?= $this->endSection() ?>
