<?= $this->extend('layouts/main') ?><?= $this->section('content') ?>
<div class="d-flex justify-content-between align-items-end page-heading"><div><div class="eyebrow">PERSONAL ATTENDANCE</div><h1>Halo, <?= esc(session('name')) ?></h1><p>Waktu absensi terverifikasi langsung oleh server WIB.</p></div><span class="badge text-bg-primary fs-6" id="clock"></span></div>
<div class="row g-3 mb-4">
 <div class="col-md-4"><div class="card stat-card h-100"><div class="card-body"><div class="text-secondary">Jam Masuk</div><div class="fs-3 fw-bold"><?= $today && $today['check_in'] ? esc(date('H:i:s',strtotime($today['check_in']))) : '—' ?></div><span class="badge text-bg-<?= ($today['check_in_status']??'')==='Terlambat'?'warning':'success' ?>"><?= esc($today['check_in_status']??'Belum hadir') ?></span><?php if($today && !empty($today['work_type'])): ?> <span class="badge text-bg-primary"><?= esc($today['work_type']) ?></span><?php endif ?></div></div></div>
 <div class="col-md-4"><div class="card stat-card h-100"><div class="card-body"><div class="text-secondary">Jam Pulang</div><div class="fs-3 fw-bold"><?= $today && $today['check_out'] ? esc(date('H:i:s',strtotime($today['check_out']))) : '—' ?></div><span class="badge text-bg-secondary"><?= esc($today['check_out_status']??'Belum pulang') ?></span></div></div></div>
 <div class="col-md-4"><div class="card stat-card h-100"><div class="card-body"><h2 class="h5 mb-3">Scan QR</h2><div class="scan-actions"><button class="btn btn-primary" id="startScan">Buka Kamera</button><button class="btn btn-outline-secondary d-none" id="stopScan">Tutup Kamera</button><button class="btn btn-outline-primary" id="scanFileBtn">Pindai Gambar</button><input class="d-none" type="file" id="qrFile" accept="image/*"></div><div id="scanStatus" class="small mt-3"></div></div></div></div>
</div>
<div id="reader" class="mx-auto"></div><div class="scan-help alert alert-info mx-auto mt-3 d-none" id="scanHelp">Arahkan QR hingga memenuhi kotak. Jarak ideal 20–40 cm, kamera harus fokus, layar QR terang, dan tidak terkena pantulan.</div>
<div class="card mt-4"><div class="card-header fw-semibold">Riwayat Terbaru</div><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Tanggal</th><th>Masuk</th><th>Tipe Kerja</th><th>Status Hadir</th><th>Pulang</th><th>Status Pulang</th><th>Lokasi</th></tr></thead><tbody><?php foreach($history as $r): ?><tr><td><?= esc($r['attendance_date']) ?></td><td><?= esc($r['check_in']?:'-') ?></td><td><?= esc($r['work_type']?:'-') ?></td><td><?= esc($r['check_in_status']?:'-') ?></td><td><?= esc($r['check_out']?:'-') ?></td><td><?= esc($r['check_out_status']?:'-') ?></td><td><?= esc($r['location_name']) ?></td></tr><?php endforeach ?></tbody></table></div></div>
<?= $this->endSection() ?><?= $this->section('scripts') ?><script src="https://unpkg.com/html5-qrcode"></script><script>
const statusEl=document.getElementById('scanStatus'),startBtn=document.getElementById('startScan'),stopBtn=document.getElementById('stopScan'),fileBtn=document.getElementById('scanFileBtn'),fileInput=document.getElementById('qrFile'),helpEl=document.getElementById('scanHelp');let scanner=null,processing=false,currentPosition=null,scanHintTimer=null;
function updateClock(){document.getElementById('clock').textContent=new Date().toLocaleTimeString('id-ID',{timeZone:'Asia/Jakarta'})+' WIB'} updateClock();setInterval(updateClock,1000);
function message(text,type='secondary'){statusEl.className=`small mt-2 text-${type}`;statusEl.textContent=text}
function requestLocation(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('Browser tidak mendukung GPS.'));navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:15000,maximumAge:0})})}
async function stopCamera(){clearTimeout(scanHintTimer);if(scanner&&scanner.isScanning){await scanner.stop()}scanner=null;startBtn.disabled=false;startBtn.classList.remove('d-none');stopBtn.classList.add('d-none');helpEl.classList.add('d-none')}
async function submitScan(token){if(processing)return;processing=true;clearTimeout(scanHintTimer);message('QR berhasil terbaca! Sedang memvalidasi absensi…','success');try{await stopCamera();const n=document.querySelector('meta[name=csrf-name]').content,h=document.querySelector('meta[name=csrf-hash]').content,res=await fetch('/api/attendance/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,latitude:currentPosition.coords.latitude,longitude:currentPosition.coords.longitude,[n]:h})}),json=await res.json();if(json.csrfHash)document.querySelector('meta[name=csrf-hash]').content=json.csrfHash;if(!res.ok)throw new Error(json.message||'Absensi gagal.');statusEl.className='alert alert-success mt-3';statusEl.textContent=json.message+' '+json.data.status;setTimeout(()=>location.reload(),1300)}catch(e){processing=false;statusEl.className='alert alert-danger mt-3';statusEl.textContent=e.message}}
async function prepareLocation(){message('Memeriksa izin dan lokasi GPS…','primary');try{currentPosition=await requestLocation();return true}catch(e){statusEl.className='alert alert-danger mt-3';statusEl.textContent=e.code===1?'GPS ditolak. Klik ikon pengaturan situs di address bar, ubah Lokasi menjadi Izinkan, lalu muat ulang halaman.':'Lokasi GPS gagal: '+e.message;return false}}
startBtn.onclick=async()=>{if(!await prepareLocation())return;startBtn.disabled=true;message('Lokasi siap. Menyiapkan kamera…','primary');try{const cameras=await Html5Qrcode.getCameras();if(!cameras.length)throw new Error('Tidak ada kamera yang ditemukan.');const preferred=cameras.find(c=>/back|rear|environment|belakang/i.test(c.label))||cameras[0];scanner=new Html5Qrcode('reader',{formatsToSupport:[Html5QrcodeSupportedFormats.QR_CODE],experimentalFeatures:{useBarCodeDetectorIfSupported:true},verbose:false});await scanner.start(preferred.id,{fps:20,qrbox:(w,h)=>{const size=Math.floor(Math.min(w,h)*0.9);return{width:size,height:size}},disableFlip:false,showTorchButtonIfSupported:true,showZoomSliderIfSupported:true,defaultZoomValueIfSupported:2},submitScan,()=>{});startBtn.classList.add('d-none');stopBtn.classList.remove('d-none');helpEl.classList.remove('d-none');message('Kamera aktif. QR belum terbaca—arahkan QR terbaru memenuhi kotak.','success');scanHintTimer=setTimeout(()=>message('QR belum terbaca. Dekatkan perlahan, tunggu fokus, naikkan kecerahan layar QR, dan hindari pantulan.','warning'),7000)}catch(e){await stopCamera();statusEl.className='alert alert-danger mt-3';statusEl.textContent='Kamera gagal dibuka: '+e.message}}
stopBtn.onclick=async()=>{processing=false;await stopCamera();message('Kamera ditutup.','secondary')};fileBtn.onclick=()=>fileInput.click();fileInput.onchange=async()=>{if(!fileInput.files.length||!await prepareLocation())return;processing=false;try{scanner=new Html5Qrcode('reader',{formatsToSupport:[Html5QrcodeSupportedFormats.QR_CODE],experimentalFeatures:{useBarCodeDetectorIfSupported:true}});const token=await scanner.scanFile(fileInput.files[0],true);await submitScan(token)}catch(e){scanner=null;statusEl.className='alert alert-danger mt-3';statusEl.textContent='QR pada gambar tidak ditemukan atau sudah tidak jelas.'}finally{fileInput.value=''}};
</script><?= $this->endSection() ?>
